# Generated by Django 4.2.3 on 2023-08-03 16:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=10), size=10),
        ),
    ]
