# Generated by Django 4.2.3 on 2023-08-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0002_alter_board_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ships_element_left',
            field=models.IntegerField(default=0),
        ),
    ]
