# Generated by Django 4.2.3 on 2023-08-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0003_board_ships_element_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='ships_element_left',
            field=models.IntegerField(default=30),
        ),
    ]
